name: build

on:
  push:
    branches:
      - dev  # forall push/merge in live
  pull_request:
    branches:
      - "**"  # forall submitted Pull Requests
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-vsu-gc-src.opam'
          - 'coq-vsu-gc-vst-32.opam'
          - 'coq-vsu-gc-vst.opam'
        image:
          - 'tcarstens/coq-vst-certigraph:8.14.1-ocaml-4.12.0-flambda--compcert-3.9--vst-2.8'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "opam pin"
              git clone https://github.com/appliedfm/coq-vsu-int_or_ptr.git ~/coq-vsu-int_or_ptr
              opam pin -n -y ~/coq-vsu-int_or_ptr
              git clone https://github.com/appliedfm/coq-certicoq-block.git ~/coq-certicoq-block
              opam pin -n -y ~/coq-certicoq-block
              git clone https://github.com/appliedfm/coq-vsu.git ~/coq-vsu
              opam pin -n -y ~/coq-vsu
              opam pin -n -y .
            endGroup